### ISSUE TITLE
Feature: User can search via term

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/Final-Project#1]
## ⚙️ Feature
User can search via a term and get related games.

## 📐 Functionality
Call the API with the user's search term and then populate the web page with the returned results

## 🖼️ Wireframes
![issue 1 a](https://user-images.githubusercontent.com/33187217/126538243-c37c3b17-4616-4ba4-b061-ec58fd280aeb.PNG)
![issue 1 b](https://user-images.githubusercontent.com/33187217/126538245-9765b9b6-adb1-49e0-bb97-1e64a0dfd6a2.PNG)
![issue 1 c](https://user-images.githubusercontent.com/33187217/126538247-7805f3d0-5482-4136-ba3d-b6c5a3c8b209.PNG)
![issue 1 d](https://user-images.githubusercontent.com/33187217/126538252-c6d9e05b-1ee0-4eff-851e-28e64db61b95.PNG)

## ✅ Task List
- [x] Create front page skeleton
- [x] Establish hash routing, so user can switch between different pages
- [x] Write JS code that can populate the page with a hardcoded search-term variable
- [x] Create a search bar that can take the text from a search bar and assign it to a variable when the search button is pressed.
- [x] Check to see if everything is working properly
- [x] Make sure user can switch between results page and search criteria page
- [x] Add CSS to polish up the look
