### ISSUE TITLE
Feature: User can search via price floor

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/Final-Project#2]
## ⚙️ Feature
User can add a minimum price to their game search and only get games above that price.

## 📐 Functionality
Call the API with the user's price floor value as the lowerPrice and then populate the web page with the returned results

## 🖼️ Wireframes
![issue 1 c](https://user-images.githubusercontent.com/33187217/126539300-4528cbf8-dde2-40f2-b48e-290c3eef5d94.PNG)

## ✅ Task List
- [x] Write JS code that can populate the page with a hardcoded price floor variable
- [x] Create an input tag that can accept price floor values and assign it to a variable when the search button is pressed
- [x] Make sure search with a price floor works in tandem with search with a term
- [x] Check to see if everything is working properly
- [x] Add CSS to polish up the look
